import pygame
import pytmx
import random

# game settings

TITLE = "ReRollRPG 2"
TILESIZE = 32
ORIGINAL_TILESIZE = 16
SCALE_FACTOR = TILESIZE / ORIGINAL_TILESIZE
GRIDWIDTH = 20
GRIDHEIGHT = 15

# UI margins
UI_MARGIN_TOP = 120
UI_MARGIN_LEFT = 150
UI_MARGIN_RIGHT = 150
UI_MARGIN_BOTTOM = 50

# game area
GAME_AREA_WIDTH = GRIDWIDTH * TILESIZE
GAME_AREA_HEIGHT = GRIDHEIGHT * TILESIZE

# game area offset
GAME_OFFSET_X = UI_MARGIN_LEFT
GAME_OFFSET_Y = UI_MARGIN_TOP

# window
WIDTH = GAME_AREA_WIDTH + UI_MARGIN_LEFT + UI_MARGIN_RIGHT
HEIGHT = GAME_AREA_HEIGHT + UI_MARGIN_TOP + UI_MARGIN_BOTTOM

FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Player
PLAYER_SPEED = 3
