import pygame
import pytmx

# game settings


WIDTH = 1280  # 2/3 of 1920
HEIGHT = 720  # 2/3 of 1080
TITLE = "ReRollRPG 2"

TILESIZE = 32
ORIGINAL_TILESIZE = 16
SCALE_FACTOR = TILESIZE / ORIGINAL_TILESIZE

# UI margins
UI_MARGIN_TOP = 120
UI_MARGIN_LEFT = 250
UI_MARGIN_RIGHT = 150
UI_MARGIN_BOTTOM = 50

# game area
GAME_AREA_WIDTH = WIDTH - UI_MARGIN_LEFT - UI_MARGIN_RIGHT
GAME_AREA_HEIGHT = HEIGHT - UI_MARGIN_TOP - UI_MARGIN_BOTTOM

# game area offset
GAME_OFFSET_X = UI_MARGIN_LEFT
GAME_OFFSET_Y = UI_MARGIN_TOP

FPS = 60

# colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# player
PLAYER_SPEED = 3

# camera
CAMERA_SMOOTHING = 0.1
