import pygame
import pytmx

# Game settings

# Window
TITLE = "ReRollRPG 2"
TILESIZE = 32
ORIGINAL_TILESIZE = 16
SCALE_FACTOR = TILESIZE / ORIGINAL_TILESIZE
GRIDWIDTH = 20
GRIDHEIGHT = 15
WIDTH = GRIDWIDTH * TILESIZE
HEIGHT = GRIDHEIGHT * TILESIZE
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Player
PLAYER_SPEED = 3
